#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumbersScrapper.DataModel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TheNumbers")]
	public partial class TheNumbersDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMovy(Movy instance);
    partial void UpdateMovy(Movy instance);
    partial void DeleteMovy(Movy instance);
    #endregion
		
		public TheNumbersDataContext() : 
				base(global::NumbersScrapper.Properties.Settings.Default.TheNumbersConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TheNumbersDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheNumbersDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheNumbersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TheNumbersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DailyBO> DailyBOs
		{
			get
			{
				return this.GetTable<DailyBO>();
			}
		}
		
		public System.Data.Linq.Table<WeeklyBO> WeeklyBOs
		{
			get
			{
				return this.GetTable<WeeklyBO>();
			}
		}
		
		public System.Data.Linq.Table<Movy> Movies
		{
			get
			{
				return this.GetTable<Movy>();
			}
		}
		
		public System.Data.Linq.Table<ReleaseDate> ReleaseDates
		{
			get
			{
				return this.GetTable<ReleaseDate>();
			}
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DailyBO")]
	public partial class DailyBO
	{
		
		private string _MovieID;
		
		private int _Rank;
		
		private double _Gross;
		
		private int _TheatersCount;
		
		private double _TotalGross;
		
		private int _NumDays;
		
		private System.DateTime _DateCounted;
		
		public DailyBO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieID
		{
			get
			{
				return this._MovieID;
			}
			set
			{
				if ((this._MovieID != value))
				{
					this._MovieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Int NOT NULL")]
		public int Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gross", DbType="Float NOT NULL")]
		public double Gross
		{
			get
			{
				return this._Gross;
			}
			set
			{
				if ((this._Gross != value))
				{
					this._Gross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatersCount", DbType="Int NOT NULL")]
		public int TheatersCount
		{
			get
			{
				return this._TheatersCount;
			}
			set
			{
				if ((this._TheatersCount != value))
				{
					this._TheatersCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalGross", DbType="Float NOT NULL")]
		public double TotalGross
		{
			get
			{
				return this._TotalGross;
			}
			set
			{
				if ((this._TotalGross != value))
				{
					this._TotalGross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDays", DbType="Int NOT NULL")]
		public int NumDays
		{
			get
			{
				return this._NumDays;
			}
			set
			{
				if ((this._NumDays != value))
				{
					this._NumDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCounted", DbType="Date NOT NULL")]
		public System.DateTime DateCounted
		{
			get
			{
				return this._DateCounted;
			}
			set
			{
				if ((this._DateCounted != value))
				{
					this._DateCounted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WeeklyBO")]
	public partial class WeeklyBO
	{
		
		private string _MovieID;
		
		private int _Rank;
		
		private double _Gross;
		
		private int _TheatersCount;
		
		private double _TotalGross;
		
		private int _NumDays;
		
		private System.DateTime _DateCounted;
		
		public WeeklyBO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieID
		{
			get
			{
				return this._MovieID;
			}
			set
			{
				if ((this._MovieID != value))
				{
					this._MovieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rank", DbType="Int NOT NULL")]
		public int Rank
		{
			get
			{
				return this._Rank;
			}
			set
			{
				if ((this._Rank != value))
				{
					this._Rank = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gross", DbType="Float NOT NULL")]
		public double Gross
		{
			get
			{
				return this._Gross;
			}
			set
			{
				if ((this._Gross != value))
				{
					this._Gross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheatersCount", DbType="Int NOT NULL")]
		public int TheatersCount
		{
			get
			{
				return this._TheatersCount;
			}
			set
			{
				if ((this._TheatersCount != value))
				{
					this._TheatersCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalGross", DbType="Float NOT NULL")]
		public double TotalGross
		{
			get
			{
				return this._TotalGross;
			}
			set
			{
				if ((this._TotalGross != value))
				{
					this._TotalGross = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumDays", DbType="Int NOT NULL")]
		public int NumDays
		{
			get
			{
				return this._NumDays;
			}
			set
			{
				if ((this._NumDays != value))
				{
					this._NumDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCounted", DbType="Date NOT NULL")]
		public System.DateTime DateCounted
		{
			get
			{
				return this._DateCounted;
			}
			set
			{
				if ((this._DateCounted != value))
				{
					this._DateCounted = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movies")]
	public partial class Movy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private int _Budget;
		
		private string _MPAARating;
		
		private int _RunningTime;
		
		private string _Franchise;
		
		private string _Genre;
		
		private string _Company;
		
		private int _RTCRating;
		
		private int _RTARating;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnBudgetChanging(int value);
    partial void OnBudgetChanged();
    partial void OnMPAARatingChanging(string value);
    partial void OnMPAARatingChanged();
    partial void OnRunningTimeChanging(int value);
    partial void OnRunningTimeChanged();
    partial void OnFranchiseChanging(string value);
    partial void OnFranchiseChanged();
    partial void OnGenreChanging(string value);
    partial void OnGenreChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnRTCRatingChanging(int value);
    partial void OnRTCRatingChanged();
    partial void OnRTARatingChanging(int value);
    partial void OnRTARatingChanged();
    #endregion
		
		public Movy()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Budget", DbType="Int NOT NULL")]
		public int Budget
		{
			get
			{
				return this._Budget;
			}
			set
			{
				if ((this._Budget != value))
				{
					this.OnBudgetChanging(value);
					this.SendPropertyChanging();
					this._Budget = value;
					this.SendPropertyChanged("Budget");
					this.OnBudgetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MPAARating", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string MPAARating
		{
			get
			{
				return this._MPAARating;
			}
			set
			{
				if ((this._MPAARating != value))
				{
					this.OnMPAARatingChanging(value);
					this.SendPropertyChanging();
					this._MPAARating = value;
					this.SendPropertyChanged("MPAARating");
					this.OnMPAARatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunningTime", DbType="Int NOT NULL")]
		public int RunningTime
		{
			get
			{
				return this._RunningTime;
			}
			set
			{
				if ((this._RunningTime != value))
				{
					this.OnRunningTimeChanging(value);
					this.SendPropertyChanging();
					this._RunningTime = value;
					this.SendPropertyChanged("RunningTime");
					this.OnRunningTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Franchise", DbType="VarChar(50)")]
		public string Franchise
		{
			get
			{
				return this._Franchise;
			}
			set
			{
				if ((this._Franchise != value))
				{
					this.OnFranchiseChanging(value);
					this.SendPropertyChanging();
					this._Franchise = value;
					this.SendPropertyChanged("Franchise");
					this.OnFranchiseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genre", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Genre
		{
			get
			{
				return this._Genre;
			}
			set
			{
				if ((this._Genre != value))
				{
					this.OnGenreChanging(value);
					this.SendPropertyChanging();
					this._Genre = value;
					this.SendPropertyChanged("Genre");
					this.OnGenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RTCRating", DbType="Int NOT NULL")]
		public int RTCRating
		{
			get
			{
				return this._RTCRating;
			}
			set
			{
				if ((this._RTCRating != value))
				{
					this.OnRTCRatingChanging(value);
					this.SendPropertyChanging();
					this._RTCRating = value;
					this.SendPropertyChanged("RTCRating");
					this.OnRTCRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RTARating", DbType="Int NOT NULL")]
		public int RTARating
		{
			get
			{
				return this._RTARating;
			}
			set
			{
				if ((this._RTARating != value))
				{
					this.OnRTARatingChanging(value);
					this.SendPropertyChanging();
					this._RTARating = value;
					this.SendPropertyChanged("RTARating");
					this.OnRTARatingChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReleaseDate")]
	public partial class ReleaseDate
	{
		
		private string _MovieID;
		
		private string _Desc;
		
		private System.DateTime _ReleaseDate1;
		
		private string _Company;
		
		private string _Remarks;
		
		public ReleaseDate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MovieID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MovieID
		{
			get
			{
				return this._MovieID;
			}
			set
			{
				if ((this._MovieID != value))
				{
					this._MovieID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desc]", Storage="_Desc", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Desc
		{
			get
			{
				return this._Desc;
			}
			set
			{
				if ((this._Desc != value))
				{
					this._Desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ReleaseDate", Storage="_ReleaseDate1", DbType="Date NOT NULL")]
		public System.DateTime ReleaseDate1
		{
			get
			{
				return this._ReleaseDate1;
			}
			set
			{
				if ((this._ReleaseDate1 != value))
				{
					this._ReleaseDate1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this._Company = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remarks", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Remarks
		{
			get
			{
				return this._Remarks;
			}
			set
			{
				if ((this._Remarks != value))
				{
					this._Remarks = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Role")]
	public partial class Role
	{
		
		private string _IDMovie;
		
		private string _Name;
		
		private string _Role1;
		
		public Role()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMovie", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string IDMovie
		{
			get
			{
				return this._IDMovie;
			}
			set
			{
				if ((this._IDMovie != value))
				{
					this._IDMovie = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Role", Storage="_Role1", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Role1
		{
			get
			{
				return this._Role1;
			}
			set
			{
				if ((this._Role1 != value))
				{
					this._Role1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
